version: "3.9"

services:
  unicom-app:
    build: .
    container_name: unicom-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      SESSION_SECRET: unicom_secret_demo
    restart: unless-stopped